[window]
decorations = "None"           # remove macOS titlebar/borders
padding = { x = 0, y = 0 }
dynamic_padding = false
startup_mode = "Windowed"
# opacity = 0.95                 # 95% opacity (slight transparency) (no borders osx)
option_as_alt = "Both"         # optional: makes Option act as Alt

[font]
size = 15.0

[colors.primary]
background = "0x000000"        # black background
foreground = "0xdddddd"        # white text faded

[env]
TERM = "xterm-256color"

[keyboard]
bindings = [
  { key = "c", mods = "Control|Shift", action = "ToggleViMode" }
]
